### ISSUE TITLE
Error on _check_sim_status

### ISSUE THREAD

**Issue by marcelomanzo** [kutu/pyirsdk#21]
Hi @kutu, I have one customer (only one from thousands) that is facing the issue below:

At first the problem would happen all the time, then I noticed that I was using an old version of the pyirsdk, I just update to latest version, the customer tried and 3 starts were successfully, but on the 4th the issue came back again.

11-16 19:20:38 SimRacingStudioApp.MainLoopThread.excepthook DEBUG    Traceback (most recent call last):
  File "backend\listeners\gameListener.py", line 464, in run
  File "backend\listeners\gameListener.py", line 551, in mainloop
  File "backend\listeners\iracingListener.py", line 19, in checkStatus
  File "irsdk.py", line 400, in startup
  File "irsdk.py", line 500, in _check_sim_status
  File "http\client.py", line 475, in read
  File "http\client.py", line 627, in _safe_read
http.client.IncompleteRead: IncompleteRead(0 bytes read, 35 more expected)

Any idea what could be causing this?

Thanks

**Comment by kutu** [comment]
try update python version

**Comment by simracingstudio** [comment]
Compiled another version using 3.10, I will get back to you if works or not.
Thanks for the suggestion
